# Generated by Django 4.0.6 on 2022-07-17 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincontent',
            name='pub_date',
        ),
    ]
