# Generated by Django 4.0.6 on 2022-07-17 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aistudent',
            name='class_num',
        ),
        migrations.RemoveField(
            model_name='aistudent',
            name='intro_text',
        ),
        migrations.RemoveField(
            model_name='aistudent',
            name='phone_num',
        ),
    ]
